title: Simge Ekiz Basar
email: simgeekiz48@gmail.com
baseurl: "" 
url: ""

# Build settings
plugins:
  - jekyll-feed


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/css"
    values:
      css: true
  - scope:
      path: "assets/js"
    values:
      js: true